apiVersion: v1
kind: Service
metadata:
    name: my-service-nodeport
spec:
    type: NodePort
    selector:
        app.kubernetes.io/name: python-deployment
    ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30007
          
